// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */

// // @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['hello'],
//     },
//   ],
//    */
// };

// module.exports = sidebars;

module.exports = {
  docs: [
    { 
      type: 'doc',
      id: 'intro',
      label: 'Introduction'
    },
    { 
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started'
    },
    { 
      type: 'category',
      label: 'Flag Management',
      items: ['flag-management/example-flow', 'flag-management/flags', 'flag-management/audiences', 'flag-management/attributes', 'flag-management/audit-history', 'flag-management/settings'],
    },
    {
      type: 'category',
      label: 'Software Development Kit (SDK)',
      items: [ 
        'sdk/sdk-keys',
        {
          type: 'category',
          label: 'React SDK',
          items: ['sdk/using-react-sdk', 'sdk/react-sdk-reference'],
        },
        {
          type: 'category',
          label: 'Node SDK',
          items: ['sdk/using-node-sdk', 'sdk/node-sdk-reference']
        }
      ]
    }
  ]
}